/*    ==脚本参数==

    源服务器版本 : SQL Server 2012 (11.0.3128)
    源数据库引擎版本 : Microsoft SQL Server Standard Edition
    源数据库引擎类型 : 独立的 SQL Server

    目标服务器版本 : SQL Server 2012
    目标数据库引擎版本 : Microsoft SQL Server Standard Edition
    目标数据库引擎类型 : 独立的 SQL Server
*/

USE [CUSDATA]
GO
/****** Object:  Table [dbo].[DEPRAT]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DEPRAT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DEPRAT](
	[F_DM] [varchar](10) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_DEPRATMC] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZJM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_SERVICE] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_SCOPE] [varchar](100) COLLATE Chinese_PRC_CI_AS NULL,
	[F_MAXDE] [float] NULL,
	[F_MINDE] [float] NULL,
	[F_DESCRIBE] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_TELEPHONE] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__DEPRAT__2C6EEFB63B572ED6] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[EMPLOYEE](
	[F_DM] [varchar](10) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_EMPLOYEENAME] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZJM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_MAXDE] [float] NULL,
	[F_MINDE] [float] NULL,
	[F_DEPRAT] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_POST] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_JOB] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_DESCRIBE] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_TELEPHONE] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__EMPLOYEE__2C6EEFB66F46A78B] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[HW]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HW]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[HW](
	[F_DM] [varchar](10) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_HWMC] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZJM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_DEFAULT] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__HW__2C6EEFB642ACDDF5] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[JSFS]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[JSFS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[JSFS](
	[F_DM] [varchar](10) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_JSFSMC] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZJM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_JC] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_PRICEINT] [int] NULL,
	[F_DEFPRICE] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__JSFS__2C6EEFB6282CE7E9] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[PATIENT]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PATIENT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PATIENT](
	[F_DM] [varchar](30) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_PATIENTNAME] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZJM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_IAMGE] [image] NULL,
	[F_IDCARD] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[F_GENDER] [varchar](2) COLLATE Chinese_PRC_CI_AS NULL,
	[F_BLOODTYPE] [varchar](3) COLLATE Chinese_PRC_CI_AS NULL,
	[F_TELEPHONE] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[F_FAMILYHISTORY] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ALLERGYHISTORY] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_INSERTDATETIME] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZD] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[F_SUMJ] [float] NULL,
	[F_SUMC] [int] NULL,
	[F_J1] [float] NULL,
	[F_J2] [float] NULL,
	[F_J3] [float] NULL,
	[F_J4] [float] NULL,
	[F_J5] [float] NULL,
	[F_J6] [float] NULL,
	[F_J7] [float] NULL,
	[F_J8] [float] NULL,
	[F_J9] [float] NULL,
	[F_J10] [float] NULL,
	[F_J11] [float] NULL,
	[F_J12] [float] NULL,
	[F_C1] [int] NULL,
	[F_C2] [int] NULL,
	[F_C3] [int] NULL,
	[F_C4] [int] NULL,
	[F_C5] [int] NULL,
	[F_C6] [int] NULL,
	[F_C7] [int] NULL,
	[F_C8] [int] NULL,
	[F_C9] [int] NULL,
	[F_C10] [int] NULL,
	[F_C11] [int] NULL,
	[F_C12] [int] NULL,
	[F_RATE] [int] NULL,
 CONSTRAINT [PK__PATIENT__2C6EEFB620091055] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[PROJECTITEMS]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROJECTITEMS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PROJECTITEMS](
	[F_TM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_DM] [varchar](30) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_PROJECTMC] [varchar](100) COLLATE Chinese_PRC_CI_AS NULL,
	[F_GG] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_CD] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_DW] [varchar](6) COLLATE Chinese_PRC_CI_AS NULL,
	[F_PACK] [varchar](6) COLLATE Chinese_PRC_CI_AS NULL,
	[F_USDW] [varchar](6) COLLATE Chinese_PRC_CI_AS NULL,
	[F_USJS] [float] NULL,
	[F_DJ1] [float] NULL,
	[F_DJ2] [float] NULL,
	[F_DJ3] [float] NULL,
	[F_DJ4] [float] NULL,
	[F_DJ5] [float] NULL,
	[F_ISPHCB] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ISKINTEST] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ISINVENTORY] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ISEVENT] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ISTEMPLATE] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ISTRUCTURE] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ISPECIAL] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_MAXSL] [float] NULL,
	[F_MINSL] [float] NULL,
	[F_MAXJJ] [float] NULL,
	[F_MINJJ] [float] NULL,
	[F_AVGJJ] [float] NULL,
	[F_MAXPC] [int] NULL,
	[F_DRIP] [int] NULL,
	[F_ZZ] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[F_GN] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[F_YF] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[F_GMP] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ISO] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_PZWH] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_BGY] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_BM] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB1] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB2] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB3] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB4] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB5] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB6] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB7] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB8] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB9] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LB10] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_UC1] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[F_UC2] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[F_UC3] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[F_UC4] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[F_UC5] [varchar](500) COLLATE Chinese_PRC_CI_AS NULL,
	[F_UN1] [int] NULL,
	[F_UN2] [int] NULL,
	[F_UN3] [int] NULL,
	[F_UN4] [int] NULL,
	[F_UN5] [int] NULL,
	[F_UF1] [float] NULL,
	[F_UF2] [float] NULL,
	[F_UF3] [float] NULL,
	[F_UF4] [float] NULL,
	[F_UF5] [float] NULL,
	[F_ATTRIBUTE1] [int] NULL,
	[F_ATTRIBUTE2] [int] NULL,
	[F_ATTRIBUTE3] [int] NULL,
	[F_ATTRIBUTE4] [int] NULL,
	[F_ATTRIBUTE5] [int] NULL,
	[F_TEXT1] [varchar](max) COLLATE Chinese_PRC_CI_AS NULL,
	[F_TEXT2] [varchar](max) COLLATE Chinese_PRC_CI_AS NULL,
	[F_TEXT3] [varchar](max) COLLATE Chinese_PRC_CI_AS NULL,
	[F_TEXT4] [varchar](max) COLLATE Chinese_PRC_CI_AS NULL,
	[F_TEXT5] [varchar](max) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__PROJECTI__2C6EEFB68FC22898] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[PROJECTYPE]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROJECTYPE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PROJECTYPE](
	[F_DM] [varchar](10) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_PROJECTYPE] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_LEVEL] [int] NULL,
	[F_ZJM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ISBOOL] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_VISIBLE] [varchar](max) COLLATE Chinese_PRC_CI_AS NULL,
	[F_DISPALY] [varchar](max) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__PROJECTY__2C6EEFB6838ED9EB] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[REISGHB]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[REISGHB]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[REISGHB](
	[F_DJH] [int] NOT NULL,
	[F_DATETIME] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[F_STATE] [varchar](4) COLLATE Chinese_PRC_CI_AS NULL,
	[F_TYPE] [varchar](4) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZLSC] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_PATIENT] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_REISLB] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_DEPRAT] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_EMPLOYEE] [varchar](10) COLLATE Chinese_PRC_CI_AS NULL,
	[F_AGE] [float] NULL,
	[F_TELEPHONE] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[F_WEIGHT] [float] NULL,
	[F_REASON] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_FAMILYHISTORY] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ALLERGYHISTORY] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_PRICE] [float] NULL,
	[F_FEE] [float] NULL,
	[F_ZD] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[F_SK] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_JZ] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_JIE] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_JZDATETIME] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
	[F_FY] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
	[F_CZ] [varchar](1) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__REISGHB__3C196CCDE8620F16] PRIMARY KEY CLUSTERED 
(
	[F_DJH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[REISLB]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[REISLB]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[REISLB](
	[F_DM] [varchar](10) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_REISLBMC] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZJM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_PRICE] [float] NULL,
	[F_FEE] [float] NULL,
	[F_DESCRIBE] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__REISLB__2C6EEFB6550BB92C] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[SFZY]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SFZY]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[SFZY](
	[F_DM] [varchar](10) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_SFZYMC] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[F_ZJM] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_SF] [varchar](2) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__SFZY__2C6EEFB6F2D38061] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[ZLSC]    Script Date: 2023/5/25 12:32:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZLSC]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ZLSC](
	[F_DM] [varchar](30) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[F_PATIENT] [varchar](30) COLLATE Chinese_PRC_CI_AS NULL,
	[F_DATETIME] [varchar](20) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK__ZLSC__2C6EEFB663CCF0E7] PRIMARY KEY CLUSTERED 
(
	[F_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
INSERT [dbo].[DEPRAT] ([F_DM], [F_DEPRATMC], [F_ZJM], [F_SERVICE], [F_SCOPE], [F_MAXDE], [F_MINDE], [F_DESCRIBE], [F_TELEPHONE]) VALUES (N'01', N'药局', N'YJ', NULL, N'药品存放', 0, 0, NULL, NULL)
GO
INSERT [dbo].[EMPLOYEE] ([F_DM], [F_EMPLOYEENAME], [F_ZJM], [F_MAXDE], [F_MINDE], [F_DEPRAT], [F_POST], [F_JOB], [F_DESCRIBE], [F_TELEPHONE]) VALUES (N'01', N'刘峰', N'LF', 0, 0, N'01', N'儿科医师', N'专家', NULL, NULL)
GO
INSERT [dbo].[HW] ([F_DM], [F_HWMC], [F_ZJM], [F_DEFAULT]) VALUES (N'01', N'药局', N'YJ', N'*')
GO
INSERT [dbo].[JSFS] ([F_DM], [F_JSFSMC], [F_ZJM], [F_JC], [F_PRICEINT], [F_DEFPRICE]) VALUES (N'01', N'零售价', N'LSJ', N'售价', 2, N'*')
GO
INSERT [dbo].[PATIENT] ([F_DM], [F_PATIENTNAME], [F_ZJM], [F_IAMGE], [F_IDCARD], [F_GENDER], [F_BLOODTYPE], [F_TELEPHONE], [F_FAMILYHISTORY], [F_ALLERGYHISTORY], [F_INSERTDATETIME], [F_ZD], [F_SUMJ], [F_SUMC], [F_J1], [F_J2], [F_J3], [F_J4], [F_J5], [F_J6], [F_J7], [F_J8], [F_J9], [F_J10], [F_J11], [F_J12], [F_C1], [F_C2], [F_C3], [F_C4], [F_C5], [F_C6], [F_C7], [F_C8], [F_C9], [F_C10], [F_C11], [F_C12], [F_RATE]) VALUES (N'00001', N'宋易', N'SY', NULL, N'210281198009301219', N'男', N'B', N'13214112212', N'-', N'-', N'2023-05-25', N'SYSTEM', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
GO
INSERT [dbo].[PROJECTITEMS] ([F_TM], [F_DM], [F_PROJECTMC], [F_GG], [F_CD], [F_DW], [F_PACK], [F_USDW], [F_USJS], [F_DJ1], [F_DJ2], [F_DJ3], [F_DJ4], [F_DJ5], [F_ISPHCB], [F_ISKINTEST], [F_ISINVENTORY], [F_ISEVENT], [F_ISTEMPLATE], [F_ISTRUCTURE], [F_ISPECIAL], [F_MAXSL], [F_MINSL], [F_MAXJJ], [F_MINJJ], [F_AVGJJ], [F_MAXPC], [F_DRIP], [F_ZZ], [F_GN], [F_YF], [F_GMP], [F_ISO], [F_PZWH], [F_BGY], [F_BM], [F_LB1], [F_LB2], [F_LB3], [F_LB4], [F_LB5], [F_LB6], [F_LB7], [F_LB8], [F_LB9], [F_LB10], [F_UC1], [F_UC2], [F_UC3], [F_UC4], [F_UC5], [F_UN1], [F_UN2], [F_UN3], [F_UN4], [F_UN5], [F_UF1], [F_UF2], [F_UF3], [F_UF4], [F_UF5], [F_ATTRIBUTE1], [F_ATTRIBUTE2], [F_ATTRIBUTE3], [F_ATTRIBUTE4], [F_ATTRIBUTE5], [F_TEXT1], [F_TEXT2], [F_TEXT3], [F_TEXT4], [F_TEXT5]) VALUES (NULL, N'100001', N'青霉素', N'100U', N'石家庄', N'支', N'合', N'万单位', 100, 0, 1.8, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[PROJECTYPE] ([F_DM], [F_PROJECTYPE], [F_LEVEL], [F_ZJM], [F_ISBOOL], [F_VISIBLE], [F_DISPALY]) VALUES (N'01', N'药品', 1, N'YP', N'*', NULL, NULL)
GO
INSERT [dbo].[PROJECTYPE] ([F_DM], [F_PROJECTYPE], [F_LEVEL], [F_ZJM], [F_ISBOOL], [F_VISIBLE], [F_DISPALY]) VALUES (N'011', N'西药', 2, N'XY', NULL, NULL, NULL)
GO
INSERT [dbo].[PROJECTYPE] ([F_DM], [F_PROJECTYPE], [F_LEVEL], [F_ZJM], [F_ISBOOL], [F_VISIBLE], [F_DISPALY]) VALUES (N'20', N'项目', 1, N'XM', N'*', NULL, NULL)
GO
INSERT [dbo].[PROJECTYPE] ([F_DM], [F_PROJECTYPE], [F_LEVEL], [F_ZJM], [F_ISBOOL], [F_VISIBLE], [F_DISPALY]) VALUES (N'201', N'挂号费', 2, N'GHF', NULL, NULL, NULL)
GO
INSERT [dbo].[REISLB] ([F_DM], [F_REISLBMC], [F_ZJM], [F_PRICE], [F_FEE], [F_DESCRIBE]) VALUES (N'01', N'平诊', N'PZ', 3, 0, NULL)
GO
INSERT [dbo].[REISLB] ([F_DM], [F_REISLBMC], [F_ZJM], [F_PRICE], [F_FEE], [F_DESCRIBE]) VALUES (N'02', N'专家', N'ZJ', 5, 0, NULL)
GO
INSERT [dbo].[REISLB] ([F_DM], [F_REISLBMC], [F_ZJM], [F_PRICE], [F_FEE], [F_DESCRIBE]) VALUES (N'03', N'义诊', N'YZ', 0, 0, NULL)
GO
INSERT [dbo].[SFZY] ([F_DM], [F_SFZYMC], [F_ZJM], [F_SF]) VALUES (N'01', N'进药入库', N'JYRK', N'S')
GO
INSERT [dbo].[SFZY] ([F_DM], [F_SFZYMC], [F_ZJM], [F_SF]) VALUES (N'02', N'销售出库', N'XSCK', N'F')
GO
INSERT [dbo].[ZLSC] ([F_DM], [F_PATIENT], [F_DATETIME]) VALUES (N'100001', N'00001', N'2023-05-25')
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__DEPRAT__F_MAXDE__34C8D9D1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[DEPRAT] ADD  CONSTRAINT [DF__DEPRAT__F_MAXDE__34C8D9D1]  DEFAULT ((0)) FOR [F_MAXDE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__DEPRAT__F_MINDE__35BCFE0A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[DEPRAT] ADD  CONSTRAINT [DF__DEPRAT__F_MINDE__35BCFE0A]  DEFAULT ((0)) FOR [F_MINDE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__EMPLOYEE__F_MAXD__38996AB5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EMPLOYEE] ADD  CONSTRAINT [DF__EMPLOYEE__F_MAXD__38996AB5]  DEFAULT ((0)) FOR [F_MAXDE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__EMPLOYEE__F_MIND__398D8EEE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EMPLOYEE] ADD  CONSTRAINT [DF__EMPLOYEE__F_MIND__398D8EEE]  DEFAULT ((0)) FOR [F_MINDE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__JSFS__F_PRICEINT__1273C1CD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[JSFS] ADD  CONSTRAINT [DF__JSFS__F_PRICEINT__1273C1CD]  DEFAULT ((0)) FOR [F_PRICEINT]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_SUMJ__4316F928]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_SUMJ__4316F928]  DEFAULT ((0)) FOR [F_SUMJ]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_SUMC__440B1D61]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_SUMC__440B1D61]  DEFAULT ((0)) FOR [F_SUMC]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J1__44FF419A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J1__44FF419A]  DEFAULT ((0)) FOR [F_J1]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J2__45F365D3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J2__45F365D3]  DEFAULT ((0)) FOR [F_J2]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J3__46E78A0C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J3__46E78A0C]  DEFAULT ((0)) FOR [F_J3]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J4__47DBAE45]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J4__47DBAE45]  DEFAULT ((0)) FOR [F_J4]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J5__48CFD27E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J5__48CFD27E]  DEFAULT ((0)) FOR [F_J5]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J6__49C3F6B7]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J6__49C3F6B7]  DEFAULT ((0)) FOR [F_J6]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J7__4AB81AF0]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J7__4AB81AF0]  DEFAULT ((0)) FOR [F_J7]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J8__4BAC3F29]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J8__4BAC3F29]  DEFAULT ((0)) FOR [F_J8]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J9__4CA06362]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J9__4CA06362]  DEFAULT ((0)) FOR [F_J9]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J10__4D94879B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J10__4D94879B]  DEFAULT ((0)) FOR [F_J10]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J11__4E88ABD4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J11__4E88ABD4]  DEFAULT ((0)) FOR [F_J11]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_J12__4F7CD00D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_J12__4F7CD00D]  DEFAULT ((0)) FOR [F_J12]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C1__5070F446]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C1__5070F446]  DEFAULT ((0)) FOR [F_C1]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C2__5165187F]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C2__5165187F]  DEFAULT ((0)) FOR [F_C2]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C3__52593CB8]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C3__52593CB8]  DEFAULT ((0)) FOR [F_C3]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C4__534D60F1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C4__534D60F1]  DEFAULT ((0)) FOR [F_C4]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C5__5441852A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C5__5441852A]  DEFAULT ((0)) FOR [F_C5]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C6__5535A963]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C6__5535A963]  DEFAULT ((0)) FOR [F_C6]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C7__5629CD9C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C7__5629CD9C]  DEFAULT ((0)) FOR [F_C7]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C8__571DF1D5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C8__571DF1D5]  DEFAULT ((0)) FOR [F_C8]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C9__5812160E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C9__5812160E]  DEFAULT ((0)) FOR [F_C9]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C10__59063A47]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C10__59063A47]  DEFAULT ((0)) FOR [F_C10]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C11__59FA5E80]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C11__59FA5E80]  DEFAULT ((0)) FOR [F_C11]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_C12__5AEE82B9]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_C12__5AEE82B9]  DEFAULT ((0)) FOR [F_C12]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PATIENT__F_RATE__5BE2A6F2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__F_RATE__5BE2A6F2]  DEFAULT ((0)) FOR [F_RATE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_USJ__1920BF5C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_USJ__1920BF5C]  DEFAULT ((0)) FOR [F_USJS]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_DJ1__1A14E395]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_DJ1__1A14E395]  DEFAULT ((0)) FOR [F_DJ1]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_DJ2__1B0907CE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_DJ2__1B0907CE]  DEFAULT ((0)) FOR [F_DJ2]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_DJ3__1BFD2C07]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_DJ3__1BFD2C07]  DEFAULT ((0)) FOR [F_DJ3]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_DJ4__1CF15040]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_DJ4__1CF15040]  DEFAULT ((0)) FOR [F_DJ4]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_DJ5__1DE57479]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_DJ5__1DE57479]  DEFAULT ((0)) FOR [F_DJ5]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_MAX__1ED998B2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_MAX__1ED998B2]  DEFAULT ((0)) FOR [F_MAXSL]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_MIN__1FCDBCEB]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_MIN__1FCDBCEB]  DEFAULT ((0)) FOR [F_MINSL]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_MAX__20C1E124]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_MAX__20C1E124]  DEFAULT ((0)) FOR [F_MAXJJ]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_MIN__21B6055D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_MIN__21B6055D]  DEFAULT ((0)) FOR [F_MINJJ]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_AVG__22AA2996]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_AVG__22AA2996]  DEFAULT ((0)) FOR [F_AVGJJ]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_MAX__239E4DCF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_MAX__239E4DCF]  DEFAULT ((0)) FOR [F_MAXPC]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UN1__24927208]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UN1__24927208]  DEFAULT ((0)) FOR [F_UN1]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UN2__25869641]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UN2__25869641]  DEFAULT ((0)) FOR [F_UN2]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UN3__267ABA7A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UN3__267ABA7A]  DEFAULT ((0)) FOR [F_UN3]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UN4__276EDEB3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UN4__276EDEB3]  DEFAULT ((0)) FOR [F_UN4]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UN5__286302EC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UN5__286302EC]  DEFAULT ((0)) FOR [F_UN5]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UF1__29572725]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UF1__29572725]  DEFAULT ((0)) FOR [F_UF1]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UF2__2A4B4B5E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UF2__2A4B4B5E]  DEFAULT ((0)) FOR [F_UF2]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UF3__2B3F6F97]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UF3__2B3F6F97]  DEFAULT ((0)) FOR [F_UF3]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UF4__2C3393D0]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UF4__2C3393D0]  DEFAULT ((0)) FOR [F_UF4]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_UF5__2D27B809]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_UF5__2D27B809]  DEFAULT ((0)) FOR [F_UF5]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_ATT__2E1BDC42]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_ATT__2E1BDC42]  DEFAULT ((0)) FOR [F_ATTRIBUTE1]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_ATT__2F10007B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_ATT__2F10007B]  DEFAULT ((0)) FOR [F_ATTRIBUTE2]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_ATT__300424B4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_ATT__300424B4]  DEFAULT ((0)) FOR [F_ATTRIBUTE3]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_ATT__30F848ED]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_ATT__30F848ED]  DEFAULT ((0)) FOR [F_ATTRIBUTE4]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PROJECTIT__F_ATT__31EC6D26]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PROJECTITEMS] ADD  CONSTRAINT [DF__PROJECTIT__F_ATT__31EC6D26]  DEFAULT ((0)) FOR [F_ATTRIBUTE5]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__REISGHB__F_AGE__68487DD7]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[REISGHB] ADD  CONSTRAINT [DF__REISGHB__F_AGE__68487DD7]  DEFAULT ((0)) FOR [F_AGE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__REISGHB__F_WEIGH__693CA210]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[REISGHB] ADD  CONSTRAINT [DF__REISGHB__F_WEIGH__693CA210]  DEFAULT ((0)) FOR [F_WEIGHT]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__REISGHB__F_PRICE__6A30C649]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[REISGHB] ADD  CONSTRAINT [DF__REISGHB__F_PRICE__6A30C649]  DEFAULT ((0)) FOR [F_PRICE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__REISGHB__F_FEE__6B24EA82]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[REISGHB] ADD  CONSTRAINT [DF__REISGHB__F_FEE__6B24EA82]  DEFAULT ((0)) FOR [F_FEE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__REISLB__F_PRICE__3D5E1FD2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[REISLB] ADD  CONSTRAINT [DF__REISLB__F_PRICE__3D5E1FD2]  DEFAULT ((0)) FOR [F_PRICE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__REISLB__F_FEE__3E52440B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[REISLB] ADD  CONSTRAINT [DF__REISLB__F_FEE__3E52440B]  DEFAULT ((0)) FOR [F_FEE]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__EMPLOYEE__F_DEPR__3A81B327]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPLOYEE]'))
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK__EMPLOYEE__F_DEPR__3A81B327] FOREIGN KEY([F_DEPRAT])
REFERENCES [dbo].[DEPRAT] ([F_DM])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__EMPLOYEE__F_DEPR__3A81B327]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPLOYEE]'))
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK__EMPLOYEE__F_DEPR__3A81B327]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_DEPRA__66603565]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB]  WITH CHECK ADD  CONSTRAINT [FK__REISGHB__F_DEPRA__66603565] FOREIGN KEY([F_DEPRAT])
REFERENCES [dbo].[DEPRAT] ([F_DM])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_DEPRA__66603565]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB] CHECK CONSTRAINT [FK__REISGHB__F_DEPRA__66603565]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_EMPLO__6754599E]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB]  WITH CHECK ADD  CONSTRAINT [FK__REISGHB__F_EMPLO__6754599E] FOREIGN KEY([F_EMPLOYEE])
REFERENCES [dbo].[EMPLOYEE] ([F_DM])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_EMPLO__6754599E]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB] CHECK CONSTRAINT [FK__REISGHB__F_EMPLO__6754599E]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_PATIE__6477ECF3]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB]  WITH CHECK ADD  CONSTRAINT [FK__REISGHB__F_PATIE__6477ECF3] FOREIGN KEY([F_PATIENT])
REFERENCES [dbo].[PATIENT] ([F_DM])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_PATIE__6477ECF3]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB] CHECK CONSTRAINT [FK__REISGHB__F_PATIE__6477ECF3]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_REISL__656C112C]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB]  WITH CHECK ADD  CONSTRAINT [FK__REISGHB__F_REISL__656C112C] FOREIGN KEY([F_REISLB])
REFERENCES [dbo].[REISLB] ([F_DM])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_REISL__656C112C]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB] CHECK CONSTRAINT [FK__REISGHB__F_REISL__656C112C]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_ZLSC__6383C8BA]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB]  WITH CHECK ADD  CONSTRAINT [FK__REISGHB__F_ZLSC__6383C8BA] FOREIGN KEY([F_ZLSC])
REFERENCES [dbo].[ZLSC] ([F_DM])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__REISGHB__F_ZLSC__6383C8BA]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB] CHECK CONSTRAINT [FK__REISGHB__F_ZLSC__6383C8BA]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__ZLSC__F_PATIENT__5EBF139D]') AND parent_object_id = OBJECT_ID(N'[dbo].[ZLSC]'))
ALTER TABLE [dbo].[ZLSC]  WITH CHECK ADD  CONSTRAINT [FK__ZLSC__F_PATIENT__5EBF139D] FOREIGN KEY([F_PATIENT])
REFERENCES [dbo].[PATIENT] ([F_DM])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__ZLSC__F_PATIENT__5EBF139D]') AND parent_object_id = OBJECT_ID(N'[dbo].[ZLSC]'))
ALTER TABLE [dbo].[ZLSC] CHECK CONSTRAINT [FK__ZLSC__F_PATIENT__5EBF139D]
GO
IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[BLOODTYPE_G323EN23445]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATIENT]'))
ALTER TABLE [dbo].[PATIENT]  WITH CHECK ADD  CONSTRAINT [BLOODTYPE_G323EN23445] CHECK  (([F_BLOODTYPE]='Rh' OR [F_BLOODTYPE]='ABO' OR [F_BLOODTYPE]='O' OR [F_BLOODTYPE]='AB' OR [F_BLOODTYPE]='B' OR [F_BLOODTYPE]='A'))
GO
IF  EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[BLOODTYPE_G323EN23445]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATIENT]'))
ALTER TABLE [dbo].[PATIENT] CHECK CONSTRAINT [BLOODTYPE_G323EN23445]
GO
IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[GENDER_G323EN23445]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATIENT]'))
ALTER TABLE [dbo].[PATIENT]  WITH CHECK ADD  CONSTRAINT [GENDER_G323EN23445] CHECK  (([F_GENDER]='女' OR [F_GENDER]='男'))
GO
IF  EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[GENDER_G323EN23445]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATIENT]'))
ALTER TABLE [dbo].[PATIENT] CHECK CONSTRAINT [GENDER_G323EN23445]
GO
IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[REISGHB_RE43623984]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB]  WITH CHECK ADD  CONSTRAINT [REISGHB_RE43623984] CHECK  (([F_STATE]='正常' OR [F_STATE]='急诊'))
GO
IF  EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[REISGHB_RE43623984]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB] CHECK CONSTRAINT [REISGHB_RE43623984]
GO
IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[REISGHB_TYPE_RT234235]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB]  WITH CHECK ADD  CONSTRAINT [REISGHB_TYPE_RT234235] CHECK  (([F_TYPE]='复诊' OR [F_TYPE]='初诊'))
GO
IF  EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[REISGHB_TYPE_RT234235]') AND parent_object_id = OBJECT_ID(N'[dbo].[REISGHB]'))
ALTER TABLE [dbo].[REISGHB] CHECK CONSTRAINT [REISGHB_TYPE_RT234235]
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'科室代码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_DEPRATMC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'科室名称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_DEPRATMC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_ZJM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'拼音助记码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_ZJM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_SERVICE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否是主要业务科室' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_SERVICE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_SCOPE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'科室业务范围' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_SCOPE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_MAXDE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最大定额' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_MAXDE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_MINDE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最低定额' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_MINDE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_DESCRIBE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'描述' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_DESCRIBE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'DEPRAT', N'COLUMN',N'F_TELEPHONE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'电话' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DEPRAT', @level2type=N'COLUMN',@level2name=N'F_TELEPHONE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'雇员代码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_EMPLOYEENAME'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'员工姓名' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_EMPLOYEENAME'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_ZJM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'拼音码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_ZJM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_MAXDE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最高定额' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_MAXDE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_MINDE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最低定额' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_MINDE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_DEPRAT'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'科室代码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_DEPRAT'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_POST'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'岗位' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_POST'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_JOB'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'职务' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_JOB'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_DESCRIBE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'描述' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_DESCRIBE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'EMPLOYEE', N'COLUMN',N'F_TELEPHONE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'电话' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'EMPLOYEE', @level2type=N'COLUMN',@level2name=N'F_TELEPHONE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'HW', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'储位代码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HW', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'HW', N'COLUMN',N'F_HWMC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'储位名称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HW', @level2type=N'COLUMN',@level2name=N'F_HWMC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'HW', N'COLUMN',N'F_ZJM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'拼音码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HW', @level2type=N'COLUMN',@level2name=N'F_ZJM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'HW', N'COLUMN',N'F_DEFAULT'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'默认储位' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HW', @level2type=N'COLUMN',@level2name=N'F_DEFAULT'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'JSFS', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'结算方式代码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'JSFS', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'JSFS', N'COLUMN',N'F_JSFSMC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'结算名称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'JSFS', @level2type=N'COLUMN',@level2name=N'F_JSFSMC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'JSFS', N'COLUMN',N'F_ZJM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'拼音码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'JSFS', @level2type=N'COLUMN',@level2name=N'F_ZJM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'JSFS', N'COLUMN',N'F_JC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'简称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'JSFS', @level2type=N'COLUMN',@level2name=N'F_JC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'JSFS', N'COLUMN',N'F_PRICEINT'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'价格' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'JSFS', @level2type=N'COLUMN',@level2name=N'F_PRICEINT'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'JSFS', N'COLUMN',N'F_DEFPRICE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'默认价格' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'JSFS', @level2type=N'COLUMN',@level2name=N'F_DEFPRICE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'病人代码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_PATIENTNAME'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'姓名' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_PATIENTNAME'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_ZJM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'拼音码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_ZJM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_IAMGE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'照片' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_IAMGE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_IDCARD'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'身份证' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_IDCARD'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_GENDER'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'性别' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_GENDER'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_BLOODTYPE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'血型' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_BLOODTYPE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_TELEPHONE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'电话' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_TELEPHONE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_FAMILYHISTORY'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'家族病史' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_FAMILYHISTORY'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_ALLERGYHISTORY'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'过敏史' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_ALLERGYHISTORY'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_INSERTDATETIME'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'增加日期' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_INSERTDATETIME'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_ZD'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'制单' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_ZD'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_SUMJ'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'合计销费' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_SUMJ'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_SUMC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'合计次数' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_SUMC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_J1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'销费一月' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_J1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_C1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'一月销费次数' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_C1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PATIENT', N'COLUMN',N'F_RATE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'等级' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PATIENT', @level2type=N'COLUMN',@level2name=N'F_RATE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_TM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'条码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_TM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'项目编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_PROJECTMC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'名称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_PROJECTMC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_GG'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'规格' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_GG'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_CD'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'产地' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_CD'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_DW'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'单位' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_DW'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_PACK'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'包装' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_PACK'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_USDW'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'使用单位' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_USDW'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_USJS'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'使用剂量' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_USJS'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_DJ1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'批发价' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_DJ1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_DJ2'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'零售价' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_DJ2'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_DJ3'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'代理价' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_DJ3'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_DJ4'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'优惠价' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_DJ4'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_DJ5'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'特惠价' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_DJ5'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ISPHCB'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否批号成本' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ISPHCB'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ISKINTEST'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否皮试' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ISKINTEST'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ISINVENTORY'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否库存' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ISINVENTORY'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ISEVENT'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否事件' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ISEVENT'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ISTEMPLATE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否模板' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ISTEMPLATE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ISTRUCTURE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否结构' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ISTRUCTURE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ISPECIAL'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否特殊' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ISPECIAL'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_MAXSL'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'库存最大数量' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_MAXSL'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_MINSL'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'库存最小数量' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_MINSL'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_MAXJJ'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最高进价' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_MAXJJ'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_MINJJ'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最低进价' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_MINJJ'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_AVGJJ'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'平均进价' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_AVGJJ'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_MAXPC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最大批次' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_MAXPC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_DRIP'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'滴速' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_DRIP'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ZZ'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'主治' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ZZ'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_GN'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'功能' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_GN'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_YF'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'用法' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_YF'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_GMP'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'GMP认证' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_GMP'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ISO'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ISO认证' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ISO'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_PZWH'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'批准文号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_PZWH'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_BGY'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'保管员' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_BGY'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_BM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'部门' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_BM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_LB1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'类别' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_LB1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_UC1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'字符' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_UC1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_UN1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'数值' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_UN1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_UF1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'浮点' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_UF1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_ATTRIBUTE1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'属性' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_ATTRIBUTE1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTITEMS', N'COLUMN',N'F_TEXT1'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'文本' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTITEMS', @level2type=N'COLUMN',@level2name=N'F_TEXT1'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTYPE', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'项目类别编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTYPE', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTYPE', N'COLUMN',N'F_PROJECTYPE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'项目类别名称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTYPE', @level2type=N'COLUMN',@level2name=N'F_PROJECTYPE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTYPE', N'COLUMN',N'F_LEVEL'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'级别' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTYPE', @level2type=N'COLUMN',@level2name=N'F_LEVEL'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTYPE', N'COLUMN',N'F_ZJM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'助记码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTYPE', @level2type=N'COLUMN',@level2name=N'F_ZJM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTYPE', N'COLUMN',N'F_ISBOOL'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否条件' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTYPE', @level2type=N'COLUMN',@level2name=N'F_ISBOOL'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTYPE', N'COLUMN',N'F_VISIBLE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'可见列' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTYPE', @level2type=N'COLUMN',@level2name=N'F_VISIBLE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'PROJECTYPE', N'COLUMN',N'F_DISPALY'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'特显列' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROJECTYPE', @level2type=N'COLUMN',@level2name=N'F_DISPALY'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_DJH'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'挂号编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_DJH'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_DATETIME'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'日期' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_DATETIME'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_STATE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'诊疗状态' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_STATE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_TYPE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'诊疗类型' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_TYPE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_ZLSC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'诊疗手册' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_ZLSC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_PATIENT'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'病人编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_PATIENT'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_REISLB'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'挂号类别' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_REISLB'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_DEPRAT'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'科室' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_DEPRAT'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_EMPLOYEE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'雇员' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_EMPLOYEE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_AGE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'年龄' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_AGE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_TELEPHONE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'电话' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_TELEPHONE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_WEIGHT'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'体重' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_WEIGHT'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_REASON'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'看诊原因' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_REASON'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_FAMILYHISTORY'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'家族病史' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_FAMILYHISTORY'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_ALLERGYHISTORY'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'过敏史' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_ALLERGYHISTORY'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_PRICE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'价格' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_PRICE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_FEE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'工本费' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_FEE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_ZD'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'制单' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_ZD'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_SK'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否收款' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_SK'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_JZ'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否接诊' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_JZ'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_JIE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'结帐' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_JIE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_JZDATETIME'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'接诊时间' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_JZDATETIME'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_FY'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'发药' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_FY'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISGHB', N'COLUMN',N'F_CZ'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'处置' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISGHB', @level2type=N'COLUMN',@level2name=N'F_CZ'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISLB', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'挂号类别代码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISLB', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISLB', N'COLUMN',N'F_REISLBMC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'挂号类别名称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISLB', @level2type=N'COLUMN',@level2name=N'F_REISLBMC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISLB', N'COLUMN',N'F_ZJM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'拼音码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISLB', @level2type=N'COLUMN',@level2name=N'F_ZJM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISLB', N'COLUMN',N'F_PRICE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'价格' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISLB', @level2type=N'COLUMN',@level2name=N'F_PRICE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISLB', N'COLUMN',N'F_FEE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'工本费' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISLB', @level2type=N'COLUMN',@level2name=N'F_FEE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'REISLB', N'COLUMN',N'F_DESCRIBE'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'描述' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REISLB', @level2type=N'COLUMN',@level2name=N'F_DESCRIBE'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'SFZY', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'收发摘要编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SFZY', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'SFZY', N'COLUMN',N'F_SFZYMC'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'摘要名称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SFZY', @level2type=N'COLUMN',@level2name=N'F_SFZYMC'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'SFZY', N'COLUMN',N'F_ZJM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'拼音码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SFZY', @level2type=N'COLUMN',@level2name=N'F_ZJM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'SFZY', N'COLUMN',N'F_SF'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'收发' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SFZY', @level2type=N'COLUMN',@level2name=N'F_SF'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'ZLSC', N'COLUMN',N'F_DM'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'诊疗手册编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ZLSC', @level2type=N'COLUMN',@level2name=N'F_DM'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'ZLSC', N'COLUMN',N'F_PATIENT'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'病人' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ZLSC', @level2type=N'COLUMN',@level2name=N'F_PATIENT'
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , N'SCHEMA',N'dbo', N'TABLE',N'ZLSC', N'COLUMN',N'F_DATETIME'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'时间' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ZLSC', @level2type=N'COLUMN',@level2name=N'F_DATETIME'
GO
