INSERT INTO DRUG (F_DRUGTM,F_DRUGMC,F_DRUGDM,F_DRUGGG,F_DRUGCD,F_DW,F_ZJM,F_SLV)
SELECT F_TM,F_SPMC,F_SPBH,F_SPGG,F_CD,F_DW,F_ZJM,F_SLV FROM JHX2019.DBO.SP



INSERT INTO HW (F_DM,F_HWMC)
 SELECT F_DM,F_MC FROM JHX2019.DBO.HW


 INSERT INTO DEPT(F_DM,F_DEPTMC)
 SELECT F_DM,F_MC FROM JHX2019.DBO.BM

 INSERT INTO EMP(F_DM,F_EMPMC,F_DEPT)
 SELECT F_DM,F_MC,F_BM FROM JHX2019.DBO.YWY

 INSERT INTO VENDOR (F_DM,F_VENDORMC,F_ZJM)
 SELECT F_DM,F_MC,F_ZJM FROM JHX2019.DBO.VENDOR
 