CREATE	TABLE	[科室]
(
	科室ID		VARCHAR(10)		NOT NULL	PRIMARY KEY,
	科室名称	VARCHAR(50)		NOT NULL,
	助记码		VARCHAR(30)			NULL,
	定额起点	FLOAT	DEFAULT	0	NULL,
	定额结束	FLOAT	DEFAULT 0	NULL,
)

CREATE	TABLE	[挂号类别]
(
	类别ID		VARCHAR(10)		NOT	NULL 	PRIMARY KEY,
	类别名称	VARCHAR(50)		NOT	NULL,
	助记码		VARCHAR(30)			NULL,
	挂号金额	FLOAT	DEFAULT	0	NULL, 
	工本费		FLOAT	DEFAULT	0	NULL,

)

CREATE	TABLE	[诊室]
(
	诊室ID		VARCHAR(10)		NOT	NULL	PRIMARY KEY,
	诊室名称	VARCHAR(50)		NOT	NULL,
	电话		VARCHAR(20)			NULL,
	助记码		VARCHAR(20)			NULL,
	定额起点	FLOAT	DEFAULT	0	NULL,
	定额结束	FLOAT	DEFAULT 0	NULL,
)

CREATE	TABLE	[职务]
(
	职务ID		VARCHAR(10)		NOT	NULL	PRIMARY KEY,
	职务名称	VARCHAR(50)			NULL,
	职衔		VARCHAR(50)			NULL,
	助记码		VARCHAR(20)			NULL,

)

CREATE	TABLE	[职员]
(
	职员ID		VARCHAR(10)		NOT	NULL	PRIMARY KEY,
	姓名		VARCHAR(50)			NULL,
	助记码		VARCHAR(20)			NULL,
	诊室ID		VARCHAR(10)REFERENCES [诊室](诊室ID) ,
	职务ID		VARCHAR(10)REFERENCES [职务](职务ID) ,
	类别ID		VARCHAR(10)REFERENCES [挂号类别](类别ID) ,
	科室ID		VARCHAR(10)REFERENCES [科室](科室ID) ,
	停用		BIT					NULL,
)

CREATE	TABLE	[权限]
(
	权限ID		VARCHAR(10)		NOT	NULL, 
	名称		VARCHAR(50)			NULL, 
	PRIMARY KEY ([权限ID]  ASC)
)

CREATE	TABLE	[操作员]
(
	职员ID		VARCHAR(10)		NOT	NULL	PRIMARY KEY,
	名称		VARCHAR(50)		NOT	NULL,
	助记码		VARCHAR(20)			NULL,
	密码		VARCHAR(20)	DEFAULT '123456'		NULL,
	权限		VARCHAR(10)REFERENCES 权限(权限ID)	NULL,
	停用		BIT					NULL,
	FOREIGN KEY (职员ID)REFERENCES	职员(职员ID) ON UPDATE CASCADE  ON DELETE CASCADE,

)

CREATE	TABLE	[挂号方式]
(
	方式ID		VARCHAR(10)		NOT NULL	PRIMARY KEY,
	方式名称	VARCHAR(50)			NULL,
	助记码		VARCHAR(20)			NULL,

)
CREATE	TABLE	[病人]
(
	病人ID		VARCHAR(20)		NOT	NULL	PRIMARY KEY,
	病人姓名	VARCHAR(50)		NOT	NULL,
	助记码		VARCHAR(20)			NULL,
	性别		VARCHAR(1)	CHECK([性别] IN ('男','女'))	DEFAULT '男',
	身份证		VARCHAR(20)			NULL,
	电话		VARCHAR(200)		NULL,
	药物过敏史	VARCHAR(200)		NULL,
	家族病史	VARCHAR(200)		NULL,

)

CREATE	TABLE	[诊疗手册]
(
	诊疗手册ID	VARCHAR(20)		NOT	NULL	PRIMARY KEY,
	使用日期	VARCHAR(10)	DEFAULT	CONVERT(VARCHAR(10),GETDATE(),120) ,
	使用时间	VARCHAR(10)	DEFAULT	CONVERT(VARCHAR(10),GETDATE(),108) ,
	患者		VARCHAR(20)	REFERENCES 病人(病人ID)	NULL,
	停用		BIT			DEFAULT	0,
)

CREATE	TABLE	[挂号]
(
	单据号				INT				NOT NULL	PRIMARY KEY,
	诊疗手册ID	VARCHAR(20) REFERENCES [诊疗手册](诊疗手册ID),
	日期		VARCHAR(10)	DEFAULT CONVERT(VARCHAR(10),GETDATE(),120)	NULL,
	时间		VARCHAR(10)	DEFAULT	CONVERT(VARCHAR(10),GETDATE(),108)	NULL,
	挂号方式	VARCHAR(10)	REFERENCES 挂号方式(方式ID)	NULL, 	
	患者		VARCHAR(20)	REFERENCES 病人(病人ID)	NULL,
	类别ID		VARCHAR(10)	REFERENCES [挂号类别](类别ID) ,
	科室ID		VARCHAR(10)	REFERENCES [科室](科室ID) ,
	诊室ID		VARCHAR(10)	REFERENCES [诊室](诊室ID) ,
	职员ID		VARCHAR(10)	REFERENCES [职员](职员ID) ,
	职务ID		VARCHAR(10)	REFERENCES [职务](职务ID) ,
	挂号金额	FLOAT	DEFAULT	0 ,
	工本费		FLOAT	DEFAULT 0,
	制单		VARCHAR(20),
)
CREATE	TABLE	[挂号属性]
(
	单据号		INT				NOT	NULL PRIMARY KEY,
	状态		VARCHAR(1)	CHECK([状态]IN ('-1','0','1','2','3','4','5','6','7','8','9')),
	接诊状态	VARCHAR(1)	CHECK([接诊状态]IN ('-1','0','1','2','3','4','5','6','7','8','9')),
	FOREIGN KEY(单据号)	REFERENCES	[挂号](单据号)	ON	UPDATE CASCADE ON DELETE CASCADE,
)
